import type { Lang } from '../../shared/i18n/lang'

/** Everything this tool says out loud. Korean typed against English. */
const en = {
  groups: {
    page: 'Page',
    text: 'Text',
    shape: 'Shape',
    join: 'Join',
    paint: 'Paint',
    variation: 'Variation',
    letters: 'Letters',
    objects: 'Objects',
    motion: 'Motion',
    export: 'Export',
  },
  draw: 'DRAW',
  select: 'SELECT',
  pasteHint: 'Paste vector SVG to use it as a path',
  dismiss: 'Dismiss',

  emptyCanvas: 'Empty canvas',
  new: 'NEW',
  presetN: (n: string) => `PRESET ${n}`,
  ground: 'Ground',
  removeImage: 'Remove image',
  scale: 'Scale',
  shiftX: 'Shift X',
  shiftY: 'Shift Y',
  dim: 'Dim',
  dropImage: 'Drop or choose an image',

  drawFirst: 'Draw a line first',
  count: 'Count',
  byGap: 'By gap',
  fitText: 'Fit text',
  start: 'Start',

  apply: 'Apply',
  all: 'All',
  selected: 'Selected',

  circle: 'Circle',
  square: 'Square',
  rounded: 'Rounded',
  size: 'Size',
  gap: 'Gap',
  corner: 'Corner',

  fillet: 'Fillet — circles keep their shape',
  metaball: 'Metaball — surfaces swell',
  radius: 'Radius',
  swell: 'Swell',
  filletNote: 'Material is added only where shapes meet. A circle stays a circle.',
  metaballNote: 'Neighbours pull the whole surface outward. Circles lose their shape.',

  fill: 'Fill',
  stroke: 'Stroke',
  line: 'Line',

  uniform: 'Uniform',
  ramp: 'Ramp',
  wave: 'Wave',
  random: 'Random',
  amount: 'Amount',
  cycles: 'Cycles',
  seed: 'Seed',
  dotsBetween: 'Dots between',
  perGap: 'Per gap',
  dotSize: 'Dot size',

  weight: 'Weight',
  colour: 'Colour',
  followPath: 'Follow path',
  baseline: 'Baseline',
  shift: 'Shift',

  clear: 'Clear',
  drawCue: 'Drag on the canvas. Shapes and letters follow the line.',
  switchToDraw: 'Switch to Draw to make one.',
  delete: 'Delete',
  resetTransform: 'Reset position, scale and rotation',
  objectPosition: 'Object position',
  rotate: 'Rotate',
  smooth: 'Smooth',

  play: 'PLAY',
  pause: 'PAUSE',
  jumpToEnd: 'Jump to the finished poster',
  parkedNote: 'Parked on a mid-play frame. Export takes it exactly as it stands.',
  playhead: 'Playhead',
  duration: 'Duration',
  pop: 'Pop',
  overshoot: 'Overshoot',
  soft: 'Soft',
  even: 'Even',
  loop: 'Loop',

  embedFont: 'Embed font',
  working: 'WORKING',

  /** Notices, raised outside a render. */
  groundImageSet: 'Image set as the ground',
  groundImageNamed: (name: string) => `Ground image: ${name}`,
  cameIn: (n: number) => `${n} outlines came in as paths`,
}

export type Copy = typeof en

const ko: Copy = {
  groups: {
    page: '지면',
    text: '글줄',
    shape: '도형',
    join: '이음',
    paint: '색',
    variation: '변주',
    letters: '글자',
    objects: '오브젝트',
    motion: '모션',
    export: '내보내기',
  },
  draw: '그리기',
  select: '선택',
  pasteHint: '벡터 SVG를 붙여넣으면 패스가 된다',
  dismiss: '닫기',

  emptyCanvas: '빈 캔버스',
  new: '새로',
  presetN: (n) => `프리셋 ${n}`,
  ground: '바탕',
  removeImage: '이미지 제거',
  scale: '배율',
  shiftX: '가로 이동',
  shiftY: '세로 이동',
  dim: '흐리기',
  dropImage: '이미지를 끌어다 놓거나 고른다',

  drawFirst: '선을 먼저 그린다',
  count: '개수',
  byGap: '간격대로',
  fitText: '글자에 맞춤',
  start: '시작 위치',

  apply: '적용 범위',
  all: '전체',
  selected: '선택한 것',

  circle: '원',
  square: '사각형',
  rounded: '둥근 사각형',
  size: '크기',
  gap: '간격',
  corner: '모서리',

  fillet: '필렛 — 원이 원으로 남는다',
  metaball: '메타볼 — 표면이 부푼다',
  radius: '반경',
  swell: '부풂',
  filletNote: '도형이 만나는 자리에만 재료가 더해진다. 원은 원으로 남는다.',
  metaballNote: '이웃이 표면 전체를 바깥으로 끌어당긴다. 원은 자기 모양을 잃는다.',

  fill: '면',
  stroke: '선',
  line: '선 두께',

  uniform: '균일',
  ramp: '점증',
  wave: '물결',
  random: '무작위',
  amount: '폭',
  cycles: '주기',
  seed: '시드',
  dotsBetween: '사이 점',
  perGap: '한 칸당',
  dotSize: '점 크기',

  weight: '굵기',
  colour: '글자색',
  followPath: '선을 따라 회전',
  baseline: '베이스라인',
  shift: '이동',

  clear: '비우기',
  drawCue: '캔버스를 끌어 본다. 도형과 글자가 그 선을 따라간다.',
  switchToDraw: '그리기로 바꾸면 만들 수 있다.',
  delete: '삭제',
  resetTransform: '위치·배율·회전 초기화',
  objectPosition: '오브젝트 위치',
  rotate: '회전',
  smooth: '다듬기',

  play: '재생',
  pause: '일시정지',
  jumpToEnd: '완성된 포스터로 건너뛴다',
  parkedNote: '재생 도중의 한 프레임에 멈춰 있다. 내보내기는 지금 이 상태를 그대로 가져간다.',
  playhead: '플레이헤드',
  duration: '길이',
  pop: '팝',
  overshoot: '오버슛',
  soft: '부드럽게',
  even: '일정하게',
  loop: '반복',

  embedFont: '폰트 내장',
  working: '작업 중',

  groundImageSet: '이미지를 바탕으로 깔았다',
  groundImageNamed: (name) => `바탕 이미지: ${name}`,
  cameIn: (n) => `윤곽선 ${n}개가 패스로 들어왔다`,
}

export const COPY: Record<Lang, Copy> = { en, ko }
